### ISSUE TITLE
HTTP Post

### ISSUE THREAD

**Issue by STSupport** [agramian/rest-api-repl-tool#6]
Hi,

I'm trying to put a file from my smartphone to an HTTP Server, but when i choose it in the Body dongle and send request, i've this message : 

"/document/primary:documents/Test.txt (No such file or directory"
Maybe i didn't put my file in the right folder ? Is there one ?

Can you help me please ?
Thank's.

**Comment by agramian** [comment]
Hi @STSupport.  Sure I can help out.  I have experienced some problems with file upload as well and was planning to fix it for a new release.

Can you give me some more details?  Is it possible for me to test against your service to reproduce the issue?  Once I have  solution I would like to send you a test build to try out and let me know if it's fixed.

**Comment by STSupport** [comment]
Good morning sir Gramian,

Thank's for answering so fast.
A screenshot is joined. Maybe, i have to put the file that i want to send in a particular folder ? Because now it's very strange, i choose my file with the explorer of the app and just after the message indicate that there is no file at this path...
Waiting to your response.

STSupport


________________________________
De : Abtin Gramian <notifications@github.com>
Envoyé : mercredi 5 juillet 2017 09:38
À : agramian/rest-api-repl-tool
Cc : STSupport; Mention
Objet : Re: [agramian/rest-api-repl-tool] HTTP Post (#6)


Hi @STSupport<https://github.com/stsupport>. Sure I can help out. I have experienced some problems with file upload as well and was planning to fix it for a new release.

Can you give me some more details? Is it possible for me to test against your service to reproduce the issue? Once I have solution I would like to send you a test build to try out and let me know if it's fixed.

**Comment by agramian** [comment]
@STSupport what is the google email/account you use for your Android device?  I would like to add you to a googla play beta user list so you can test a new build to see if the file handling works properly for you before I release it to everyone on the production version.

**Comment by agramian** [comment]
@STSupport I just released a new version of the app that should have the file upload functionality fixed.  Please test it out and let me know if it works for you as well.
