### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by vertigobo** [agramian/rest-api-repl-tool#7]
Hi. Excellent work.
I am not able to select and upload a file.
I think the binary body option shoud trigger a file selection input.

**Comment by agramian** [comment]
Thanks @vertigobo for the kind words. 

Currently file uploads only work with `form-data` as the data type.  You would click into the key/value row and see a radio button where you can select "file" and then trigger selection of a file from your device.

Let me know if it works.

**Comment by vertigobo** [comment]
Yes, it works.
Moreover, it makes perfect sense! :-)

**Comment by agramian** [comment]
@vertigobo if you have a chance I would greatly appreciate if you could please leave a review for the app.

**Comment by vertigobo** [comment]
@agramian Done right now.

**Comment by agramian** [comment]
Thanks @vertigobo and let me know if you run into any other issues or have suggestions.
